# Generated by Django 6.0.2 on 2026-03-04 09:44

from django.db import migrations, models


def seed_default_courts(apps, schema_editor):
    Court = apps.get_model("core", "Court")
    default_courts = [
        {"number": 1, "surface": "hard", "indoors": False},
        {"number": 2, "surface": "hard", "indoors": False},
        {"number": 3, "surface": "clay", "indoors": False},
        {"number": 4, "surface": "grass", "indoors": True},
    ]
    for payload in default_courts:
        Court.objects.get_or_create(number=payload["number"], defaults=payload)


def remove_seeded_courts(apps, schema_editor):
    Court = apps.get_model("core", "Court")
    Court.objects.filter(number__in=[1, 2, 3, 4]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('surface', models.CharField(choices=[('hard', 'Hard'), ('clay', 'Clay'), ('grass', 'Grass')], default='hard', max_length=10)),
                ('indoors', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('maintenance_start', models.DateField(blank=True, null=True)),
                ('maintenance_end', models.DateField(blank=True, null=True)),
                ('maintenance_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.RunPython(seed_default_courts, remove_seeded_courts),
    ]
