# Generated by Django 6.0.2 on 2026-03-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='closing_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='court',
            name='opening_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
